// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_CPUEspatial_TMBExports
#include <TMB.hpp>
#include "SpatailTemporaCPUENN.hpp"
#include "SpatialTemporalCPUE.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "SpatailTemporaCPUENN") {
    return SpatailTemporaCPUENN(this);
  } else if(model == "SpatialTemporalCPUE") {
    return SpatialTemporalCPUE(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
